instrument: EUR_USD

timeframe: D

strategy:
  name: VolumeOBVCMF
  params:
    volume_short_window: 20
    volume_long_window: 60
    obv_window: 30
    cmf_window: 20
    cmf_threshold: 0.05
    take_profit: 100
    stop_loss: 50

broker:
  name: OandaV20
  params:
    environment: practice
    account_id: your_account_id
    access_token: your_access_token

sizer:
  name: FixedRisk
  params:
    risk: 0.02
